PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS raw_aaa_opendata_rechargeable (
    ingest_id INTEGER PRIMARY KEY AUTOINCREMENT,
    codgeo TEXT,
    libgeo TEXT,
    epci TEXT,
    libepci TEXT,
    date_arrete TEXT,
    nb_vp_rechargeables_el TEXT,
    nb_vp_rechargeables_gaz TEXT,
    nb_vp TEXT,
    source_file TEXT NOT NULL,
    loaded_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS raw_tableau_synthetique_coproff (
    ingest_id INTEGER PRIMARY KEY AUTOINCREMENT,
    nom_reg TEXT,
    code_reg TEXT,
    nom_dep TEXT,
    code_dep TEXT,
    code_epci TEXT,
    nom_epci TEXT,
    code_com TEXT,
    nom_commune TEXT,
    nb_copros TEXT,
    nb_logements TEXT,
    copros_5_moins TEXT,
    copros_6_10 TEXT,
    copros_11_20 TEXT,
    copros_21_50 TEXT,
    copros_51_200 TEXT,
    copros_200_plus TEXT,
    copros_avant_49 TEXT,
    copros_49_74 TEXT,
    copros_75_2000 TEXT,
    copros_2000_plus TEXT,
    copros_annee_na TEXT,
    taux_immat TEXT,
    source_file TEXT NOT NULL,
    loaded_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS raw_population_insee (
    ingest_id INTEGER PRIMARY KEY AUTOINCREMENT,
    code_insee TEXT,
    population_totale TEXT,
    pop_15_29 TEXT,
    pop_60_74 TEXT,
    pop_75_89 TEXT,
    pop_90_plus TEXT,
    residences_principales TEXT,
    logements_vacants TEXT,
    logements_locatifs TEXT,
    pop_sans_diplome TEXT,
    pop_bac TEXT,
    pop_bac_plus_2 TEXT,
    pop_bac_plus_5 TEXT,
    pop_active TEXT,
    pop_chomeurs TEXT,
    pop_inactifs TEXT,
    revenu_median TEXT,
    taux_pauvrete TEXT,
    nb_beneficiaires_rsa TEXT,
    nb_allocataires_minimum_vieillesse TEXT,
    nb_allocataires_famille TEXT,
    nb_minima_sociaux TEXT,
    nb_aides_logement TEXT,
    source_file TEXT NOT NULL,
    loaded_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS raw_mapping (
    ingest_id INTEGER PRIMARY KEY AUTOINCREMENT,
    code_insee TEXT,
    code_postal TEXT,
    nom_commune TEXT,
    departement TEXT,
    source_file TEXT NOT NULL,
    loaded_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS raw_rnc_data_gouv_with_qpv (
    ingest_id INTEGER PRIMARY KEY AUTOINCREMENT,
    epci TEXT,
    commune TEXT,
    numero_d_immatriculation TEXT,
    date_d_immatriculation TEXT,
    date_de_la_derniere_maj TEXT,
    type_de_syndic_benevole_professionnel_non_connu TEXT,
    identification_du_representant_legal_raison_sociale_et_le_numer TEXT,
    raison_sociale_du_representant_legal TEXT,
    siret_du_representant_legal TEXT,
    code_ape TEXT,
    commune_du_representant_legal TEXT,
    mandat_en_cours_dans_la_copropriete TEXT,
    date_de_fin_du_dernier_mandat TEXT,
    nom_d_usage_de_la_copropriete TEXT,
    adresse_de_reference TEXT,
    numero_et_voie_adresse_de_reference TEXT,
    code_postal_adresse_de_reference TEXT,
    commune_adresse_de_reference TEXT,
    adresse_complementaire_1 TEXT,
    adresse_complementaire_2 TEXT,
    adresse_complementaire_3 TEXT,
    nombre_d_adresses_complementaires TEXT,
    long TEXT,
    lat TEXT,
    date_du_reglement_de_copropriete TEXT,
    residence_service TEXT,
    syndicat_cooperatif TEXT,
    syndicat_principal_ou_syndicat_secondaire TEXT,
    si_secondaire_n_d_immatriculation_du_principal TEXT,
    nombre_d_asl_auxquelles_est_rattache_le_syndicat_de_coproprieta TEXT,
    nombre_d_aful_auxquelles_est_rattache_le_syndicat_de_copropriet TEXT,
    nombre_d_unions_de_syndicats_auxquelles_est_rattache_le_syndica TEXT,
    nombre_total_de_lots TEXT,
    nombre_total_de_lots_a_usage_d_habitation_de_bureaux_ou_de_comm TEXT,
    nombre_de_lots_a_usage_d_habitation TEXT,
    nombre_de_lots_de_stationnement TEXT,
    periode_de_construction TEXT,
    reference_cadastrale_1 TEXT,
    code_insee_commune_1 TEXT,
    prefixe_1 TEXT,
    section_1 TEXT,
    numero_parcelle_1 TEXT,
    reference_cadastrale_2 TEXT,
    code_insee_commune_2 TEXT,
    prefixe_2 TEXT,
    section_2 TEXT,
    numero_parcelle_2 TEXT,
    reference_cadastrale_3 TEXT,
    code_insee_commune_3 TEXT,
    prefixe_3 TEXT,
    section_3 TEXT,
    numero_parcelle_3 TEXT,
    nombre_de_parcelles_cadastrales TEXT,
    nom_qp_2015 TEXT,
    code_qp_2015 TEXT,
    nom_qp_2024 TEXT,
    code_qp_2024 TEXT,
    copro_dans_acv TEXT,
    copro_dans_pvd TEXT,
    code_de_pdp TEXT,
    copro_dans_pdp TEXT,
    copro_aidee TEXT,
    code_officiel_commune TEXT,
    nom_officiel_commune TEXT,
    code_officiel_arrondissement_commune TEXT,
    nom_officiel_arrondissement_commune TEXT,
    code_officiel_epci TEXT,
    nom_officiel_epci TEXT,
    code_officiel_departement TEXT,
    nom_officiel_departement TEXT,
    code_officiel_region TEXT,
    nom_officiel_region TEXT,
    source_file TEXT NOT NULL,
    loaded_at TEXT NOT NULL DEFAULT (datetime('now'))
);
